"""Report generation - Markdown and professional HTML."""

from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Template

from audit_readiness.config import Config
from audit_readiness.utils import logger


MARKDOWN_TEMPLATE = """# AUDIT READINESS REPORT - {{ project_name }}
> **Generated by Foundry Audit Readiness v{{ version }}** — 7 Security Tools  
> Date: {{ date }}

---

## 1. STATIC ANALYSIS SUITE (7 Tools)

{% for tool, result in static_analysis.items() %}
### {{ tool.upper() }}
{%- if result.error %}
- **Status:** [SKIPPED] {{ result.error }}
{%- else %}
{%- set critical = result.findings | selectattr("severity", "equalto", "critical") | list | length %}
{%- set high = result.findings | selectattr("severity", "equalto", "high") | list | length %}
{%- set medium = result.findings | selectattr("severity", "equalto", "medium") | list | length %}
{%- set low = result.findings | selectattr("severity", "equalto", "low") | list | length %}
{%- set info = result.findings | selectattr("severity", "equalto", "info") | list | length %}
- **Findings:** {{ critical }} critical | {{ high }} high | {{ medium }} medium | {{ low }} low | {{ info }} info
- **Status:** {% if result.passed %}:white_check_mark: PASS{% else %}:x: FAIL{% endif %}

{%- if result.findings %}
| Severity | File | Line | Check | Message |
|----------|------|------|-------|---------|
{%- for finding in result.findings[:20] %}
| {{ finding.severity }} | {{ finding.file or "-" }} | {{ finding.line or "-" }} | {{ finding.check }} | {{ finding.message | replace("|", " ") | replace("\\n", " ") | truncate(100, end="") }} |
{%- endfor %}
{%- if result.findings | length > 20 %}
| ... | ... | ... | ... | *{{ result.findings | length - 20 }} more findings truncated* |
{%- endif %}
{%- endif %}
{%- endif %}

---
{%- endfor %}

## 2. TEST COVERAGE

| Metric | Value | Threshold | Status |
|--------|-------|-----------|--------|
| Line Coverage | {{ coverage.line_percent | round(1) }}% | {{ config.coverage.line }}% | {% if coverage.line_percent >= config.coverage.line %}:white_check_mark: PASS{% else %}:x: FAIL{% endif %} |
| Branch Coverage | {{ coverage.branch_percent | round(1) }}% | {{ config.coverage.branch }}% | {% if coverage.branch_percent >= config.coverage.branch %}:white_check_mark: PASS{% else %}:x: FAIL{% endif %} |
| Function Coverage | {{ coverage.function_percent | round(1) }}% | {{ config.coverage.function }}% | {% if coverage.function_percent >= config.coverage.function %}:white_check_mark: PASS{% else %}:x: FAIL{% endif %} |

---

## 3. INVARIANT TESTS

{%- if invariants.functions_found > 0 %}
- **Invariant functions detected:** {{ invariants.functions_found }}
- **All passing:** {{ invariants.all_passed }}
- **Fuzz runs:** {{ invariants.runs }}
{%- else %}
- **No invariant tests found.** (Optional check)
{%- endif %}

---

## 4. CODE QUALITY

### NatDoc / NatSpec
- **Public:** {{ natspec.documented_public }}/{{ natspec.total_public }} documented
- **External:** {{ natspec.documented_external }}/{{ natspec.total_external }} documented
- **Method:** {{ natspec.method }}

{%- if not natspec.passed %}
**Missing documentation ({{ natspec.missing | length }} functions):**
{%- for file, func, line in natspec.missing %}
- `{{ file }}:{{ line }}` — `{{ func }}()`
{%- endfor %}
{%- endif %}

### Compiler Warnings
{%- if no_warnings %}
- **Status:** :white_check_mark: No warnings detected
{%- else %}
- **Status:** :x: Warnings detected ({{ compiler_warnings | length }} warning(s))
{%- for warning in compiler_warnings %}
```
{{ warning }}
```
{%- endfor %}
{%- endif %}

### Gas Snapshots
{%- if gas.baseline_exists %}
- **Baseline exists:** {{ gas.functions | length }} functions tracked
{%- else %}
- **No baseline found.** Run `forge snapshot` to establish one.
{%- endif %}

---

## 5. TOOL COVERAGE SUMMARY

| # | Tool | Type | Status |
|---|------|------|--------|
| 1 | Slither | Static Analysis | {% if static_analysis.slither and static_analysis.slither.passed %}:white_check_mark:{% elif static_analysis.slither %}:x:{% else %}:grey_question:{% endif %} |
| 2 | Aderyn | Static Analysis | {% if static_analysis.aderyn and static_analysis.aderyn.passed %}:white_check_mark:{% elif static_analysis.aderyn %}:x:{% else %}:grey_question:{% endif %} |
| 3 | Solhint | Linter | {% if static_analysis.solhint and static_analysis.solhint.passed %}:white_check_mark:{% elif static_analysis.solhint %}:x:{% else %}:grey_question:{% endif %} |
| 4 | Semgrep | Rule Engine | {% if static_analysis.semgrep and static_analysis.semgrep.passed %}:white_check_mark:{% elif static_analysis.semgrep %}:x:{% else %}:grey_question:{% endif %} |
| 5 | Mythril | Symbolic Execution | {% if static_analysis.mythril and static_analysis.mythril.passed %}:white_check_mark:{% elif static_analysis.mythril %}:x:{% else %}:grey_question:{% endif %} |
| 6 | Halmos | Formal Verification | {% if static_analysis.halmos and static_analysis.halmos.passed %}:white_check_mark:{% elif static_analysis.halmos %}:x:{% else %}:grey_question:{% endif %} |
| 7 | SMTChecker | SMT Verification | {% if static_analysis.smtchecker and static_analysis.smtchecker.passed %}:white_check_mark:{% elif static_analysis.smtchecker %}:x:{% else %}:grey_question:{% endif %} |

---

## 6. FINAL VERDICT

{%- set all_passed = static_analysis_passed and coverage_passed and natspec.passed and no_warnings %}
{%- if all_passed %}
# :white_check_mark: STATUS: READY FOR PROFESSIONAL AUDIT

Your codebase passed all checks across 7 security tools. A professional audit should proceed smoothly.

**Estimated audit time reduction:** 30-40%
{%- else %}
# :x: STATUS: NOT READY FOR AUDIT

The following must be resolved:
{%- if not static_analysis_passed %}
- Fix critical/high findings from static analysis (7 tools)
{%- endif %}
{%- if not coverage_passed %}
- Increase test coverage to meet thresholds
{%- endif %}
{%- if not natspec.passed %}
- Document all public/external functions with NatSpec
{%- endif %}
{%- if not no_warnings %}
- Eliminate compiler warnings
{%- endif %}
{%- endif %}

---

*This report was generated automatically by foundry-audit-readiness v{{ version }}.*
*It does NOT replace a professional security audit. It prepares your code before engaging an auditor.*
"""


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Audit Readiness Report - {{ project_name }}</title>
<style>
  :root {
    --bg: #0f172a;
    --fg: #e2e8f0;
    --muted: #94a3b8;
    --accent: #38bdf8;
    --pass: #34d399;
    --fail: #f87171;
    --warn: #fbbf24;
    --card: #1e293b;
    --border: #334155;
  }
  * { box-sizing: border-box; }
  body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    line-height: 1.6;
    max-width: 1100px;
    margin: 0 auto;
    padding: 30px 20px;
    color: var(--fg);
    background: var(--bg);
  }
  h1 {
    color: var(--accent);
    border-bottom: 3px solid var(--accent);
    padding-bottom: 15px;
    font-size: 2rem;
    margin-bottom: 10px;
  }
  h1 .version { font-size: 0.9rem; color: var(--muted); font-weight: normal; }
  h2 {
    color: var(--accent);
    margin-top: 40px;
    border-bottom: 2px solid var(--border);
    padding-bottom: 10px;
    font-size: 1.5rem;
  }
  h3 { color: #94a3b8; font-size: 1.2rem; margin-top: 30px; padding: 8px 12px; background: var(--card); border-radius: 6px; border-left: 4px solid var(--accent); }
  table { border-collapse: collapse; width: 100%; margin: 20px 0; font-size: 0.92rem; }
  th, td { border: 1px solid var(--border); padding: 10px 12px; text-align: left; }
  th { background: var(--card); font-weight: 600; color: var(--accent); }
  tr:nth-child(even) { background: rgba(30,41,59,0.5); }
  tr:hover { background: rgba(56,189,248,0.05); }
  code { background: var(--card); padding: 2px 8px; border-radius: 4px; font-size: 0.88em; font-family: 'SF Mono', Consolas, monospace; color: #fbbf24; }
  pre { background: var(--card); padding: 15px; border-radius: 8px; overflow-x: auto; border: 1px solid var(--border); }
  .status-pass { color: var(--pass); font-weight: 600; }
  .status-fail { color: var(--fail); font-weight: 600; }
  .status-skip { color: var(--warn); font-weight: 600; }
  .summary-box { background: rgba(52,211,153,0.08); border: 2px solid var(--pass); border-radius: 12px; padding: 25px; margin: 25px 0; text-align: center; }
  .summary-box.fail { background: rgba(248,113,113,0.08); border-color: var(--fail); }
  .summary-box h2 { border: none; margin-top: 0; }
  blockquote { border-left: 4px solid var(--accent); margin: 0; padding: 10px 20px; color: var(--muted); font-style: italic; background: var(--card); border-radius: 0 8px 8px 0; }
  .print-btn { position: fixed; top: 20px; right: 20px; background: var(--accent); color: #0f172a; border: none; padding: 12px 24px; border-radius: 8px; cursor: pointer; font-size: 0.95rem; font-weight: 600; box-shadow: 0 4px 12px rgba(56,189,248,0.3); }
  .print-btn:hover { background: #7dd3fc; }
  .tool-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 0.8rem; font-weight: 600; margin: 2px; }
  .badge-pass { background: rgba(52,211,153,0.15); color: var(--pass); border: 1px solid rgba(52,211,153,0.3); }
  .badge-fail { background: rgba(248,113,113,0.15); color: var(--fail); border: 1px solid rgba(248,113,113,0.3); }
  .badge-skip { background: rgba(251,191,36,0.15); color: var(--warn); border: 1px solid rgba(251,191,36,0.3); }
  .meta { color: var(--muted); font-size: 0.9rem; }
  @media print { .print-btn { display: none; } body { background: #fff; color: #1f2937; } }
</style>
</head>
<body>
  <button class="print-btn" onclick="window.print()">Save as PDF</button>
  {{ html_content | safe }}
</body>
</html>
"""


def generate_markdown_report(
    project_name: str,
    version: str,
    date: str,
    config: Config,
    static_analysis: Dict,
    coverage: Any,
    invariants: Any,
    natspec: Any,
    gas: Any,
    no_warnings: bool,
    compiler_warnings: Optional[List[str]] = None,
) -> str:
    """Render the Markdown report from template."""
    template = Template(MARKDOWN_TEMPLATE)

    static_analysis_passed = all(
        r.passed for r in static_analysis.values() if not r.error
    ) if static_analysis else True

    coverage_passed = (
        coverage.line_percent >= config.coverage.line
        and coverage.branch_percent >= config.coverage.branch
        and coverage.function_percent >= config.coverage.function
    )

    sanitized_warnings = [w.replace("`", "'") for w in (compiler_warnings or [])]

    return template.render(
        project_name=project_name,
        version=version,
        date=date,
        config=config,
        static_analysis=static_analysis,
        coverage=coverage,
        invariants=invariants,
        natspec=natspec,
        gas=gas,
        no_warnings=no_warnings,
        compiler_warnings=sanitized_warnings,
        static_analysis_passed=static_analysis_passed,
        coverage_passed=coverage_passed,
    )


def generate_html_report(markdown_content: str, output_path: Path) -> None:
    """Convert Markdown report to professional dark-themed HTML."""
    import markdown as mdlib
    html_body = mdlib.markdown(markdown_content, extensions=["tables", "fenced_code"])

    template = Template(HTML_TEMPLATE)
    full_html = template.render(html_content=html_body)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(full_html, encoding="utf-8")
    logger.info(f"HTML report saved to {output_path}")


def save_report(content: str, output_path: Path) -> None:
    """Save report to file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    logger.info(f"Report saved to {output_path}")
