"""Report generation - Markdown and self-contained HTML."""

from pathlib import Path
from typing import Any, Dict, List, Optional

from jinja2 import Template

from audit_readiness.config import Config
from audit_readiness.utils import logger


MARKDOWN_TEMPLATE = """# AUDIT READINESS REPORT - {{ project_name }}
> Generated by Foundry Audit Readiness v{{ version }}  
> Date: {{ date }}

---

## 1. STATIC ANALYSIS

{%- for tool, result in static_analysis.items() %}
### {{ tool.title() }}
{%- if result.error %}
- **Error:** {{ result.error }}
{%- else %}
{%- set critical = result.findings | selectattr("severity", "equalto", "critical") | list | length %}
{%- set high = result.findings | selectattr("severity", "equalto", "high") | list | length %}
{%- set medium = result.findings | selectattr("severity", "equalto", "medium") | list | length %}
{%- set low = result.findings | selectattr("severity", "equalto", "low") | list | length %}
- **Summary:** {{ critical }} critical, {{ high }} high, {{ medium }} medium, {{ low }} low
{%- if not result.passed %}
- **Status:** FAILED (critical/high findings detected)
{%- else %}
- **Status:** PASS
{%- endif %}

{%- if result.findings %}
**Detailed findings:**

| Severity | File | Line | Check | Message |
|----------|------|------|-------|---------|
{%- for finding in result.findings %}
| {{ finding.severity }} | {{ finding.file or "—" }} | {{ finding.line or "—" }} | {{ finding.check }} | {{ finding.message | replace("|", " ") | replace("\n", " ") | truncate(120, end="") }} |
{%- endfor %}
{%- endif %}
{%- endif %}
{%- else %}
- No static analysis tools configured.
{%- endfor %}

---

## 2. TEST COVERAGE

| Metric | Value | Threshold | Status |
|--------|-------|-----------|--------|
| Line Coverage | {{ coverage.line_percent | round(1) }}% | {{ config.coverage.line }}% | {% if coverage.line_percent >= config.coverage.line %}<span class="status-pass">PASS</span>{% else %}<span class="status-fail">FAIL</span>{% endif %} |
| Branch Coverage | {{ coverage.branch_percent | round(1) }}% | {{ config.coverage.branch }}% | {% if coverage.branch_percent >= config.coverage.branch %}<span class="status-pass">PASS</span>{% else %}<span class="status-fail">FAIL</span>{% endif %} |
| Function Coverage | {{ coverage.function_percent | round(1) }}% | {{ config.coverage.function }}% | {% if coverage.function_percent >= config.coverage.function %}<span class="status-pass">PASS</span>{% else %}<span class="status-fail">FAIL</span>{% endif %} |

---

## 3. INVARIANT TESTS

{%- if invariants.functions_found > 0 %}
- **Invariant functions detected:** {{ invariants.functions_found }}
- **All passing:** {{ invariants.all_passed }}
- **Fuzz runs:** {{ invariants.runs }}
{%- else %}
- **No invariant tests found.** (Optional check — not blocking by default.)
{%- endif %}

---

## 4. CODE QUALITY

### NatDoc / NatSpec

- **Public:** {{ natspec.documented_public }}/{{ natspec.total_public }} documented
- **External:** {{ natspec.documented_external }}/{{ natspec.total_external }} documented
- **Method:** {{ natspec.method }}

{%- if not natspec.passed %}
**Missing documentation ({{ natspec.missing | length }} functions):**

{%- for file, func, line in natspec.missing %}
- `{{ file }}:{{ line }}` — `{{ func }}()`
{%- endfor %}
{%- endif %}

### Compiler Warnings

{%- if no_warnings %}
- **Status:** No warnings detected
{%- else %}
- **Status:** Warnings detected ({{ compiler_warnings | length }} warning(s))

**All warnings:**

{%- for warning in compiler_warnings %}
```
{{ warning }}
```
{%- endfor %}
{%- endif %}

### Gas Snapshots

{%- if gas.baseline_exists %}
- **Baseline exists:** {{ gas.functions | length }} functions tracked
{%- else %}
- **No baseline found.** Run `forge snapshot` to establish one.
{%- endif %}

---

## 5. SUMMARY

{%- set all_passed = static_analysis_passed and coverage_passed and natspec.passed and no_warnings %}
{%- if all_passed %}
# STATUS: READY FOR PROFESSIONAL AUDIT

Your codebase meets all quality thresholds. A professional audit should proceed smoothly.

**Estimated audit time reduction:** 30–40%
{%- else %}
# STATUS: NOT READY FOR AUDIT

The following issues must be resolved before engaging an auditor:

{%- if not static_analysis_passed %}
- Fix critical/high findings from static analysis
{%- endif %}
{%- if not coverage_passed %}
- Increase test coverage to meet thresholds
{%- endif %}
{%- if not natspec.passed %}
- Document all public/external functions with NatSpec
{%- endif %}
{%- if not no_warnings %}
- Eliminate compiler warnings
{%- endif %}
{%- endif %}

---

*This report was generated automatically. It does not replace a professional security audit.*
"""


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Audit Readiness Report - {{ project_name }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; max-width: 900px; margin: 40px auto; padding: 20px; color: #1f2937; background: #fff; }
  h1 { color: #111827; border-bottom: 3px solid #2563eb; padding-bottom: 12px; font-size: 1.8rem; }
  h2 { color: #2563eb; margin-top: 35px; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; font-size: 1.4rem; }
  h3 { color: #4b5563; font-size: 1.15rem; margin-top: 25px; }
  table { border-collapse: collapse; width: 100%; margin: 20px 0; font-size: 0.95rem; }
  th, td { border: 1px solid #d1d5db; padding: 10px 12px; text-align: left; }
  th { background: #f9fafb; font-weight: 600; color: #374151; }
  tr:nth-child(even) { background: #f9fafb; }
  code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; font-family: 'SF Mono', Monaco, monospace; }
  .status-pass { color: #059669; font-weight: 600; }
  .status-fail { color: #dc2626; font-weight: 600; }
  .summary-box { background: #f0fdf4; border: 1px solid #86efac; border-radius: 8px; padding: 20px; margin: 20px 0; }
  .summary-box.fail { background: #fef2f2; border-color: #fca5a5; }
  blockquote { border-left: 4px solid #2563eb; margin: 0; padding-left: 15px; color: #6b7280; font-style: italic; }
  .print-btn { position: fixed; top: 20px; right: 20px; background: #2563eb; color: white; border: none; padding: 10px 20px; border-radius: 6px; cursor: pointer; font-size: 0.9rem; }
  .print-btn:hover { background: #1d4ed8; }
  @media print { .print-btn { display: none; } body { margin: 0; } }
</style>
</head>
<body>
  <button class="print-btn" onclick="window.print()">Save as PDF</button>
  {{ html_content | safe }}
</body>
</html>
"""


def generate_markdown_report(
    project_name: str,
    version: str,
    date: str,
    config: Config,
    static_analysis: Dict,
    coverage: Any,
    invariants: Any,
    natspec: Any,
    gas: Any,
    no_warnings: bool,
    compiler_warnings: Optional[List[str]] = None,
) -> str:
    """Render the Markdown report from template."""
    template = Template(MARKDOWN_TEMPLATE)

    static_analysis_passed = all(
        r.passed for r in static_analysis.values() if not r.error
    )
    coverage_passed = (
        coverage.line_percent >= config.coverage.line
        and coverage.branch_percent >= config.coverage.branch
        and coverage.function_percent >= config.coverage.function
    )

    sanitized_warnings = [w.replace("`", "'") for w in (compiler_warnings or [])]

    return template.render(
        project_name=project_name,
        version=version,
        date=date,
        config=config,
        static_analysis=static_analysis,
        coverage=coverage,
        invariants=invariants,
        natspec=natspec,
        gas=gas,
        no_warnings=no_warnings,
        compiler_warnings=sanitized_warnings,
        static_analysis_passed=static_analysis_passed,
        coverage_passed=coverage_passed,
    )


def generate_html_report(markdown_content: str, output_path: Path) -> None:
    """Convert Markdown report to self-contained HTML with print-to-PDF button."""
    import markdown as mdlib
    html_body = mdlib.markdown(markdown_content, extensions=["tables", "fenced_code"])

    template = Template(HTML_TEMPLATE)
    full_html = template.render(html_content=html_body)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(full_html, encoding="utf-8")
    logger.info(f"HTML report saved to {output_path}")


def save_report(content: str, output_path: Path) -> None:
    """Save report to file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    logger.info(f"Report saved to {output_path}")
